events {}

http {
    server {
        listen 80;

        location /market-data/sub2/ {
            proxy_pass http://host.docker.internal:4088/;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Important for Blazor (WebSockets / SignalR)
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            rewrite ^/market-data/sub2/(.*)$ /$1 break;
        }
    }
}